### ISSUE TITLE
TimelineService get exceptions for deleted items

### ISSUE THREAD

**Issue by KancerEzeroglu** [leadlet/leadlet-api#11]
https://github.com/leadlet/leadlet-api/blob/master/src/main/java/com/leadlet/service/impl/TimelineServiceImpl.java#L87

```
2018-04-09 16:03:52.080 ERROR 12449 --- [ XNIO-2 task-18] com.leadlet.aop.logging.LoggingAspect    : Exception in com.leadlet.web.rest.TimelineResource.getPersonTimelines() with cause = 'NULL' and exception = 'Unable to find com.leadlet.domain.Document with id 15'

javax.persistence.EntityNotFoundException: Unable to find com.leadlet.domain.Document with id 15
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$JpaEntityNotFoundDelegate.handleEntityNotFound(EntityManagerFactoryBuilderImpl.java:158)
        at org.hibernate.proxy.AbstractLazyInitializer.checkTargetState(AbstractLazyInitializer.java:235)
        at org.hibernate.proxy.AbstractLazyInitializer.initialize(AbstractLazyInitializer.java:157)
        at org.hibernate.proxy.AbstractLazyInitializer.getImplementation(AbstractLazyInitializer.java:259)
        at org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer.invoke(JavassistLazyInitializer.java:73)

```
```
2018-04-09 15:57:03.028 DEBUG 12424 --- [  XNIO-2 task-7] com.leadlet.aop.logging.LoggingAspect    : Exit: com.leadlet.web.rest.PersonResource.getPerson() with result = <200 OK,PersonDTO{id=100, name='Juli', address='Bucklan', title='jbucklan0@blogtalkradio.com', organization=OrganizationDTO{id=1023, name='checksm', address='488 Stephen Crossing', phones=[OrganizationPhoneDTO{id=23, phone='+3513038039161', type=OTHER, organizationId=null}], email='null'}, phones=[], email='jbucklan0@huffingtonpost.com'},{}>
2018-04-09 15:57:03.033 DEBUG 12424 --- [  XNIO-2 task-9] com.leadlet.aop.logging.LoggingAspect    : Exit: com.leadlet.service.ActivityService.findByPersonId() with result = Page 1 of 1 containing com.leadlet.service.dto.ActivityDTO instances
2018-04-09 15:57:03.044 DEBUG 12424 --- [  XNIO-2 task-9] com.leadlet.aop.logging.LoggingAspect    : Exit: com.leadlet.web.rest.ActivityResource.getActivitiesByPersonId() with result = <200 OK,[ActivityDTO{id=629, title='erat vestibulum sed magna at nunc commodo placerat', memo='ante ipsum primis in faucibus', start=2018-01-02 00:00:00.0, end=2018-01-11 00:00:00.0, type=EMAIL, deal=com.leadlet.service.dto.DealDTO@a4, person=PersonDTO{id=100, name='Juli', address='Bucklan', title='jbucklan0@blogtalkradio.com', organization=OrganizationDTO{id=1023, name='checksm', address='488 Stephen Crossing', phones=[OrganizationPhoneDTO{id=23, phone='+3513038039161', type=OTHER, organizationId=null}], email='null'}, phones=[], email='jbucklan0@huffingtonpost.com'}, organization=OrganizationDTO{id=1024, name='ncarmodyn', address='5294 South Park', phones=[OrganizationPhoneDTO{id=24, phone='+305818789839', type=WORK, organizationId=null}], email='null'}, agent=UserDTO{id=13, login='sdrewes3@cdc.gov', firstName='Sioux', lastName='Drewes', imageUrl='', activated=true, langKey='en', createdBy='null', createdDate=null, lastModifiedBy='null', lastModifiedDate=null, authorities=[com.leadlet.service.dto.AuthorityDTO@cedde4e3], teamId=11}, location=null, done=false, closedDate=null}, ActivityDTO{id=1002, title='taskJuli', memo='deneme', start=2018-04-07 10:30:00.0, end=2018-04-07 12:00:00.0, type=TASK, deal=com.leadlet.service.dto.DealDTO@84, person=PersonDTO{id=100, name='Juli', address='Bucklan', title='jbucklan0@blogtalkradio.com', organization=OrganizationDTO{id=1023, name='checksm', address='488 Stephen Crossing', phones=[OrganizationPhoneDTO{id=23, phone='+3513038039161', type=OTHER, organizationId=null}], email='null'}, phones=[], email='jbucklan0@huffingtonpost.com'}, organization=OrganizationDTO{id=1023, name='checksm', address='488 Stephen Crossing', phones=[OrganizationPhoneDTO{id=23, phone='+3513038039161', type=OTHER, organizationId=null}], email='null'}, agent=UserDTO{id=11, login='hpendered1@sakura.ne.jp', firstName='Hyacinthe', lastName='Pendered', imageUrl='', activated=true, langKey='en', createdBy='null', createdDate=null, lastModifiedBy='null', lastModifiedDate=null, authorities=[com.leadlet.service.dto.AuthorityDTO@cedde4e3], teamId=31}, location=null, done=false, closedDate=null}, ActivityDTO{id=1004, title='call juli', memo='deneme', start=2018-04-07 14:00:00.0, end=2018-04-07 17:30:00.0, type=CALL, deal=com.leadlet.service.dto.DealDTO@83, person=PersonDTO{id=100, name='Juli', address='Bucklan', title='jbucklan0@blogtalkradio.com', organization=OrganizationDTO{id=1023, name='checksm', address='488 Stephen Crossing', phones=[OrganizationPhoneDTO{id=23, phone='+3513038039161', type=OTHER, organizationId=null}], email='null'}, phones=[], email='jbucklan0@huffingtonpost.com'}, organization=OrganizationDTO{id=1023, name='checksm', address='488 Stephen Crossing', phones=[OrganizationPhoneDTO{id=23, phone='+3513038039161', type=OTHER, organizationId=null}], email='null'}, agent=UserDTO{id=10, login='bfurmonger0@xinhuanet.com', firstName='Bartie', lastName='Furmonger', imageUrl='', activated=true, langKey='en', createdBy='null', createdDate=null, lastModifiedBy='null', lastModifiedDate=null, authorities=[com.leadlet.service.dto.AuthorityDTO@cedde4e3], teamId=12}, location=null, done=false, closedDate=null}],{X-Total-Count=[3], Link=[</api/activities?page=0&size=20>; rel="last",</api/activities?page=0&size=20>; rel="first"]}>
2018-04-09 15:57:03.071 ERROR 12424 --- [  XNIO-2 task-5] com.leadlet.aop.logging.LoggingAspect    : Exception in com.leadlet.service.TimelineService.findByPersonId() with cause = 'NULL' and exception = 'Unable to find com.leadlet.domain.Document with id 15'

javax.persistence.EntityNotFoundException: Unable to find com.leadlet.domain.Document with id 15
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$JpaEntityNotFoundDelegate.handleEntityNotFound(EntityManagerFactoryBuilderImpl.java:158)
	at org.hibernate.proxy.AbstractLazyInitializer.checkTargetState(AbstractLazyInitializer.java:235)
	at org.hibernate.proxy.AbstractLazyInitializer.initialize(AbstractLazyInitializer.java:157)
	at org.hibernate.proxy.AbstractLazyInitializer.getImplementation(AbstractLazyInitializer.java:259)
	at org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer.invoke(JavassistLazyInitializer.java:73)
	at com.leadlet.domain.Document_$$_jvst343_11.getId(Document_$$_jvst343_11.java)
	at com.leadlet.service.mapper.DocumentMapperImpl.toDto(DocumentMapperImpl.java:78)
	at com.leadlet.service.impl.TimelineServiceImpl.lambda$findByPersonId$1(TimelineServiceImpl.java:107)
	at org.springframework.data.domain.Chunk.getConvertedContent(Chunk.java:168)
	at org.springframework.data.domain.PageImpl.map(PageImpl.java:104)
	at com.leadlet.service.impl.TimelineServiceImpl.findByPersonId(TimelineServiceImpl.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
```

**Comment by ygokirmak** [comment]
Timeservice and frontend logic rewritten. lets check for new erros
